# Generated by Django 5.2.7 on 2026-01-02 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_blocked_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Used only for FARMER verification'),
        ),
    ]
